package com.gael.gael_practica1.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF00696B)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF9CF1F3)
val onPrimaryContainerLight = Color(0xFF004F51)
val secondaryLight = Color(0xFF4A6363)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFCCE8E8)
val onSecondaryContainerLight = Color(0xFF324B4C)
val tertiaryLight = Color(0xFF4C5F7C)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFD4E3FF)
val onTertiaryContainerLight = Color(0xFF354863)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF4FBFA)
val onBackgroundLight = Color(0xFF161D1D)
val surfaceLight = Color(0xFFF4FBFA)
val onSurfaceLight = Color(0xFF161D1D)
val surfaceVariantLight = Color(0xFFDAE4E4)
val onSurfaceVariantLight = Color(0xFF3F4949)
val outlineLight = Color(0xFF6F7979)
val outlineVariantLight = Color(0xFFBEC8C8)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2B3231)
val inverseOnSurfaceLight = Color(0xFFECF2F1)
val inversePrimaryLight = Color(0xFF80D4D6)